### ISSUE TITLE
Provide stylua.toml with explicit formatting conventions

### ISSUE THREAD

**Issue by seflue** [chipsenkbeil/org-roam.nvim#43]
When I tried to make some changes to the code, I realized, that my formatter settings are not compatible with the projects one, it reformats all the code. To make it easy to contribute, it would be very beneficial to provide these settings as a stylua.toml.

**Comment by chipsenkbeil** [comment]
I've never used stylua. I think the only formatting that happens is provided by the Lua language server's defaults. Could look into providing that file when I have time to look into more details about it. :smile:

**Comment by seflue** [comment]
I just did some research. I think, the best way is to provide a `.editorconfig` which is configured in a way, that stylua and lua-language-server format it exactly in the same way. Then it would not matter, if the individual developer is just using the formatting feature from lua-language-server or stylua via [none-ls](https://github.com/nvimtools/none-ls.nvim/blob/main/doc/BUILTINS.md#stylua).
I will continue to research to find some common ground between the current formatting, stylua and EmmyLuaCodeStyle.

**Comment by seflue** [comment]
There is also a [Github Action](https://github.com/JohnnyMorganz/stylua-action) and [pre-commit-hook](https://github.com/JohnnyMorganz/StyLua/blob/main/.pre-commit-hooks.yaml) for stylua.

What setup would you prefer? Adding a [pre-commit](https://pre-commit.com) hook or just relying that a developer would use either stylua or lua-language-server for formatting? We could add the stylua GH action to the pipeline just to check. That's what [nvim-orgmode](https://github.com/nvim-orgmode/orgmode/blob/6c03b725285cdcb6fae26c6e465637fdbac4f32e/.github/workflows/tests.yml#L17-L24) does.

We could also provide both, a stylua.toml and an .editorconfig (like nvim-orgmode).

**Comment by chipsenkbeil** [comment]
> What setup would you prefer?

Personally, I like having there be a failure if your PR doesn't match expected formatting, rather than doing the formatting for you. So I'd rely on someone to use stylua or the lua language server to do the formatting, or just hand-format based on the error messages from a github action.

Also, if nvim-orgmode has a stylua, we could just follow that one and do a big reformat of the plugin to follow it. I really don't mind which way we go 😄

**Comment by seflue** [comment]
I created a PR: #44. Please give me a sign, that you commited/merged all your intermediate code changes, than I will do the reformatting and the branch can be merged. I just want to avoid big merge conflicts with ongoing changes on your side (I just know the pain :sweat_smile:).

**Comment by chipsenkbeil** [comment]
> I created a PR: #44. Please give me a sign, that you commited/merged all your intermediate code changes, than I will do the reformatting and the branch can be merged. I just want to avoid big merge conflicts with ongoing changes on your side (I just know the pain :sweat_smile:).

Now active commits or branches on my side. You're good to go.
