### ISSUE TITLE
Support "prefix" option for keymappings

### ISSUE THREAD

**Issue by seflue** [chipsenkbeil/org-roam.nvim#46]
The orgmode plugin supports a [prefix option](https://github.com/nvim-orgmode/orgmode/blob/master/DOCS.md#mappings) to define a common prefix for orgmode to provide easy customization of the prefix without forcing the user to redefine a lot of keymappings.
In org-roam `<Leader>n` is a very common prefix for most of the operations, so it would make sense to provide the same feature.
@chipsenkbeil Would you be open to such a feature? If so, I would proceed with building it, because I really miss this. :wink:

**Comment by chipsenkbeil** [comment]
Go for it :)

**Comment by seflue** [comment]
As I am working on it I discovered, that you are using `<Leader>`, but in some cases also `<LocalLeader>`. Was this intensional? If so, we should also provide a `localprefix`. I would then default `prefix = "<Leader>n"` and `localprefix = "<LocalLeader>n`.
