### ISSUE TITLE
An issue occurred while closing a buffer that is still in use

### ISSUE THREAD

**Issue by xinmodao** [chipsenkbeil/org-roam.nvim#50]
![image](https://github.com/chipsenkbeil/org-roam.nvim/assets/12230820/e06e4320-c11d-4bad-b1aa-9252cb639b15)

Hello! Thank you very much for sharing!
I'm configuration of arhclinx+dwm+kitty+neovim10.0+Lazyvim
I create a new node that can only be recorded in a temporary file. Buffer needs to be closed to trigger confirmation.
There is no information in the prompt box, and there are too many error messages to close. I closed noicn.vim, but there was still an error message
error message is reported:
E315: ml_get: Invalid lnum: 1
noice.nvim ....local/share/nvim/lazy/nui.nvim/lua/nui/popup/border.lua:502: Vim:E937: Attempt to delete a buffer that is in use: /tmp/nvim.aaha/QhdcKG/3.org

**Comment by chipsenkbeil** [comment]
Hm, E315: ml_get is typically an issue internally with neovim. Regardless, if it's being triggered by capturing a new node and it's related to closing the capture buffer, this is probably an issue to file with [nvim-orgmode](https://github.com/nvim-orgmode/orgmode).

This plugin uses [nvim-orgmode](https://github.com/nvim-orgmode/orgmode) to capture nodes.

@kristijanhusak any thoughts here? I remember hitting this error at some point with nvim-orgmode as well.

**Comment by kristijanhusak** [comment]
Similar thing was reported here https://github.com/nvim-orgmode/orgmode/pull/758.

Does it happen without noice?

**Comment by chipsenkbeil** [comment]
> Similar thing was reported here https://github.com/nvim-orgmode/orgmode/pull/758.
> 
> Does it happen without noice?
> 
> Edit: Also, which Neovim version is this?

Reporter says neovim 0.10. I've encountered on 0.9.5.

**Comment by chipsenkbeil** [comment]
@kristijanhusak is there a way to transfer this issue over to the orgmode repo? If not, I'll close this out and we can piggyback on the issue you brought up earlier.

**Comment by chipsenkbeil** [comment]
> @chipsenkbeil we can use the one I linked. 
> Are you able to reproduce this without noice?

When I encountered the issue, I didn't have noice installed, but I haven't run into it in awhile and may have avoided it with some scheduling. Let's move the conversation to your issue.
