### ISSUE TITLE
How to disable completion in org-roam select buffer

### ISSUE THREAD

**Issue by seflue** [chipsenkbeil/org-roam.nvim#52]
I have buffer completions enabled with nvim-cmp. Unfortunately they are also active in the selection buffer, which is very annoying. I am now searching for a way to identify the org-roam selection buffer within my implementation of the `enabled` function, which can be passed as an option to nvim-cmp's `setup` function.
I'm searching through the codes for some clues. I disabled completion for all buffers of buftype `prompt`. 

@chipsenkbeil Can we set the buftype of the selection buffer to `prompt` or the filetype to something, which can be simply identified? Or do you have other suggestions for this problem?

**Comment by seflue** [comment]
I found a quickfix for me: Disabling completion for `buftype == "nofile"`.

This disables completion for Telescope and org-roam selection buffer.
``` lua
require("hrsh7th/nvim-cmp").setup({
  enabled = function()
    local buftype = vim.api.nvim_get_option_value("buftype", { buf = 0 })
    return buftype ~= "prompt" and buftype ~= "nofile"
  end 
})
```

**Comment by chipsenkbeil** [comment]
I don't believe I set a file type today, but I don't see a problem with providing something like `org-roam-select`. You want to take a look at adding what you need to select.lua when it creates the window and buffer?

**Comment by chipsenkbeil** [comment]
> Actually you name the buffer, which can be also used to identify it. We can add a hint to the documentation. I will create a PR for this.
> 
> 

Oh, lol. You know it's obscure if I forgot that I did that. :smile:

**Comment by seflue** [comment]
> Oh, lol. You know it's obscure if I forgot that I did that. 😄

It's absolutely not. Related to what I've implemented my head is also acting like a flow heater. And I think every serious programmer is very familiar with this phenomenon. :sweat_smile: 

I extended the docs a little bit and also tested the generation. 

Actually the workflow I used is not ideal:
1. I added an intermediate commit including my branch into the docs Github action
2. I pulled the automatically created docs and checked it.
3. I fixed the docs, reset the branch and repeated
4. When I was satisfied I reset the branch a last time.

Beside that I wasn't able to create working cross references. I also looked for some existing ones and found out, that they also don't work in neovims help buffer. I think, this is an issue with panvimdoc when a targeted file is not Markdown. Actually I think, the underlying issue lies even deeper, in the pandoc converter from Org to Markdown itself. 

Because you already wrote a lot of documentation in org format, how is your experience with it and how satisfied are you with the result of the conversion? Are there any general suggestions to keep the links intact in Org as well as in the resulting vimdoc?

**Comment by chipsenkbeil** [comment]
> Because you already wrote a lot of documentation in org format, how is your experience with it and how satisfied are you with the result of the conversion? Are there any general suggestions to keep the links intact in Org as well as in the resulting vimdoc?

It's okay, but there are definitely details of what panvimdoc can generate that leave me wanting for more, especially when using org syntax which has even more limited support. I chose to write the README and DOCS files in org syntax to force myself to dogfood the [nvim-orgmode](https://github.com/nvim-orgmode/orgmode) plugin, and like the idea that other could browse the documentation in a more familiar setting than a vim help buffer; however, links and headings aren't the nicest.

I don't want to go back to writing vim help documentation manually, which I've done in other plugins, as it's a pain and gets out of sync faster for me. But I'm open to suggestions or alternatives if we want to look for them.

**Comment by seflue** [comment]
> I don't want to go back to writing vim help documentation manually, which I've done in other plugins, as it's a pain and gets out of sync faster for me. But I'm open to suggestions or alternatives if we want to look for them.

I understand that completely. I actually had a look at the documentation of panvimdoc and it seems, that they have some explicitly recommended syntax for Markdown files, which are transfered nicely to vimdoc. I also looked at other plugins, which use panvimdoc and they seem to be able to create really nice vimdocs from their Markdown files.

I will try out, if the notation features mentioned in the panvimdoc documentation can be translated to some Org syntax, which just works. If this is possible, a short section in the contribution documentation would be enough.

Otherwise, I think, the best way would be to translate the Org docs to Markdown with pandoc, fix the issues, which prevent a smooth vimdoc transformation manually and then stick to Markdown documentation files in combination with panvimdoc.

**Comment by wenjinnn** [comment]
After commit [192732](https://github.com/chipsenkbeil/org-roam.nvim/commit/192732a8de167e7770b12db31e737239311b1a43) you could disable cmp comletion by filetype, this does not affect other plugins:
```lua
  require("cmp").setup.filetype({ "org-roam-select" }, {
    enabled = false,
  })

```
