### ISSUE TITLE
 UI wordwrap in "org-roam find"

### ISSUE THREAD

**Issue by HotdogFighter** [chipsenkbeil/org-roam.nvim#56]
Bug: Each entry in the org-roam-select prompt (Leader n f ) takes up two lines instead of one.

I was having a bit of weirdness on my Windows 10 machine (nvim 0.9.5), so I made a barebones nvim install with only 0.1.0 orgroam and 0.3.4 orgmode. Looked and functioned **great**! Also tried with the most up to date commit of both plugins (orgroam 45153562e7bfe806d84747d6518cad714c63ca2e, orgmode cc51c1914e3f0bf20bd543a7176df5bab12ec247). **Still smooth!**

So I ported over things from my personal nvim init.lua to the barebones config until I found the culprit. The setting that broke the UI: **vim.opt.signcolumn = 'yes'**

Here's a couple screenshots to clarify. The barebones install:
<img width="482" alt="without" src="https://github.com/chipsenkbeil/org-roam.nvim/assets/136388492/0dccc69e-7670-47b7-a141-b4d315954b2a">
The barebones install with **vim.opt.signcolumn = 'yes'**:
<img width="482" alt="with" src="https://github.com/chipsenkbeil/org-roam.nvim/assets/136388492/e9620d0a-2b4e-4e21-bd82-7ef2aa535ce8">

Anyway, just a small bug in an otherwise killer plugin. Your youtube video overview was super helpful in showcasing the features and workflow and I transitioned immediately from my _system_ of scattered txt files. Thanks for sharing this plugin.

**Comment by chipsenkbeil** [comment]
Thanks for the bug report and glad you like it!

This sounds like what https://github.com/chipsenkbeil/org-roam.nvim/pull/45 fixed, which is upstream of the 0.1.0 tag of this plugin.

If you think this fixes your issue, we can look at tagging a 0.1.1 release.

**Comment by HotdogFighter** [comment]
Oh wow, I must've not sync'd Lazy after updating init.lua with the latest commits. This totally fixes the issue. Big ups 👍
